### ISSUE TITLE
Do konstruktoru patří pouze inicializace instance. Rozhodně by neměla házet exception. Kod patri do metody pro ziskani mapy.

### ISSUE THREAD

**Issue by vanamir2** [primaERP/pt-translations#2]
https://github.com/primaERP/pt-translations/blob/31c0892438b429241921ac92bd0ec5b0a1d9595d/src/main/java/PropertiesInputLoader.java#L15-L28

**Comment by ViktorHohin** [comment]
Nebylo by potom rozumnejsi udelat `InputLoader` jako statickou tridu, tj mit jen metodu `getStrings(File f)`, ktera nacte soubor a vrati mapu? Tedko mame uplne zbytecne konstruktor, ktery bere `File` jako parametr.

**Comment by ViktorHohin** [comment]
`InputLoader` prepsan na statickou tridu jen pro nacitani vstupu.
