### ISSUE TITLE
Naming convention

### ISSUE THREAD

**Issue by vanamir2** [primaERP/pt-translations#3]
https://github.com/primaERP/pt-translations/blob/31c0892438b429241921ac92bd0ec5b0a1d9595d/src/main/java/PropertiesInputLoader.java#L25

Naming convention:
![image](https://user-images.githubusercontent.com/38475469/133219071-97847a24-8e9a-416d-a581-febbe1789f29.png)

![image](https://user-images.githubusercontent.com/38475469/133219053-f466d18d-8579-49ab-922b-0457f7f839dd.png)

Zdroj:
https://www.youtube.com/watch?v=2a_ytyt9sf8&t=3011s

**Comment by ViktorHohin** [comment]
`String[] ls` je pouzit jen na dvou radcich, ihned pod sebou. Je skutecne nutne vymyslet delsi/lepsi pojmenovani?

https://github.com/primaERP/pt-translations/blob/31c0892438b429241921ac92bd0ec5b0a1d9595d/src/main/java/PropertiesInputLoader.java#L25-L26

**Comment by vanamir2** [comment]
Pokud bude vše ostatní dodávat dostatečný kontext, není to potřeba. Tady by klidně mohlo být něco jako "translationKeyValue" , ale nechám na tobě. Nebylo to jediné místo, kde bylo pojmenování dost strohé.
