### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by vanamir2** [primaERP/pt-translations#4]
https://github.com/primaERP/pt-translations/blob/31c0892438b429241921ac92bd0ec5b0a1d9595d/src/main/java/FileTranslator.java#L6-L37

Klidně bych provedl inicializaci jazyka v konstruktoru a pak nechal volání translate s parametry source a target file.

Čitelnější bude, když se kód rozdělí do menších bloků. Platí, že všechna volání v daném scope by měla být na stejné úrovni abstrakce. Metoda by tedy klidně mohla být rozepsána

        PropertiesInputLoader loader = new PropertiesInputLoader(new File(source_file));
        Map<String, String> map = loader.getStrings();
        map.entrySet().forEach(  entry ->  translateLine(entry));

**Comment by ViktorHohin** [comment]
Refaktorovano, commit 391923f
