### ISSUE TITLE
Deklarovaná třída by měla být InputLoader namísto PropertiesInputLoader

### ISSUE THREAD

**Issue by vanamir2** [primaERP/pt-translations#7]
https://github.com/primaERP/pt-translations/blob/31c0892438b429241921ac92bd0ec5b0a1d9595d/src/main/java/FileTranslator.java#L11

zamysli se nad tím proč (v návaznosti na SOLID - Dependency inversion principle)

**Comment by ViktorHohin** [comment]
`InputLoader` refaktorovan, nyni staticka trida.
