### ISSUE TITLE
Definoval bych nějaký ENUM/konstanty pro všechny dostupné jazyky na DeepL.

### ISSUE THREAD

**Issue by vanamir2** [primaERP/pt-translations#9]
https://github.com/primaERP/pt-translations/blob/31c0892438b429241921ac92bd0ec5b0a1d9595d/src/test/java/TranslatorTest.java#L10

Nebo pokud to lze, tak např dotáhnout přímo z DeepL seznam všech dostupných jazyků a zkusit nějaký testovací překlad pro každý jazyk.

**Comment by ViktorHohin** [comment]
DeepL api nevypada ze ma nejaky request na vypis vsech moznych translaci.

Pridan `Translator` interface a do nej vypis moznych jazyku. https://github.com/primaERP/pt-translations/blob/master/src/main/java/Translator.java

Mozna by bylo vhodnejsi vypis jazyku dat primo do `DeepLTranslator`?

**Comment by vanamir2** [comment]
Možná už to vypadá jinak, nevýhodou tohoto řešení přes definici jednotlivých stringů je ztížená možnost ověření scénářů:
je CZ na seznamu podporovaných jazyků? V tom je výhodnější použít nějakou strukturu - ENUM / immutable množinu stringů.
